// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/criminal_intent_protos.proto

package com.bignerdranch.android.criminalintent.models.raw;

public final class CriminalIntentProtos {
  private CriminalIntentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CrimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bignerdranch.android.criminalintent.models.raw.Crime)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required int64 createdDate = 3;</code>
     */
    boolean hasCreatedDate();
    /**
     * <code>required int64 createdDate = 3;</code>
     */
    long getCreatedDate();

    /**
     * <code>required bool solved = 4;</code>
     */
    boolean hasSolved();
    /**
     * <code>required bool solved = 4;</code>
     */
    boolean getSolved();
  }
  /**
   * Protobuf type {@code com.bignerdranch.android.criminalintent.models.raw.Crime}
   */
  public static final class Crime extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.bignerdranch.android.criminalintent.models.raw.Crime)
      CrimeOrBuilder {
    // Use Crime.newBuilder() to construct.
    private Crime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Crime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Crime defaultInstance;
    public static Crime getDefaultInstance() {
      return defaultInstance;
    }

    public Crime getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Crime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              createdDate_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              solved_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.class, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder.class);
    }

    public static com.google.protobuf.Parser<Crime> PARSER =
        new com.google.protobuf.AbstractParser<Crime>() {
      public Crime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Crime(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Crime> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDDATE_FIELD_NUMBER = 3;
    private long createdDate_;
    /**
     * <code>required int64 createdDate = 3;</code>
     */
    public boolean hasCreatedDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 createdDate = 3;</code>
     */
    public long getCreatedDate() {
      return createdDate_;
    }

    public static final int SOLVED_FIELD_NUMBER = 4;
    private boolean solved_;
    /**
     * <code>required bool solved = 4;</code>
     */
    public boolean hasSolved() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool solved = 4;</code>
     */
    public boolean getSolved() {
      return solved_;
    }

    private void initFields() {
      id_ = "";
      title_ = "";
      createdDate_ = 0L;
      solved_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreatedDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSolved()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, createdDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, solved_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, createdDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, solved_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bignerdranch.android.criminalintent.models.raw.Crime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bignerdranch.android.criminalintent.models.raw.Crime)
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.class, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder.class);
      }

      // Construct using com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        createdDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        solved_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor;
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime getDefaultInstanceForType() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.getDefaultInstance();
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime build() {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime buildPartial() {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime result = new com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.createdDate_ = createdDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.solved_ = solved_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime) {
          return mergeFrom((com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime other) {
        if (other == com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasCreatedDate()) {
          setCreatedDate(other.getCreatedDate());
        }
        if (other.hasSolved()) {
          setSolved(other.getSolved());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasCreatedDate()) {
          
          return false;
        }
        if (!hasSolved()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private long createdDate_ ;
      /**
       * <code>required int64 createdDate = 3;</code>
       */
      public boolean hasCreatedDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 createdDate = 3;</code>
       */
      public long getCreatedDate() {
        return createdDate_;
      }
      /**
       * <code>required int64 createdDate = 3;</code>
       */
      public Builder setCreatedDate(long value) {
        bitField0_ |= 0x00000004;
        createdDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 createdDate = 3;</code>
       */
      public Builder clearCreatedDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createdDate_ = 0L;
        onChanged();
        return this;
      }

      private boolean solved_ ;
      /**
       * <code>required bool solved = 4;</code>
       */
      public boolean hasSolved() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool solved = 4;</code>
       */
      public boolean getSolved() {
        return solved_;
      }
      /**
       * <code>required bool solved = 4;</code>
       */
      public Builder setSolved(boolean value) {
        bitField0_ |= 0x00000008;
        solved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool solved = 4;</code>
       */
      public Builder clearSolved() {
        bitField0_ = (bitField0_ & ~0x00000008);
        solved_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bignerdranch.android.criminalintent.models.raw.Crime)
    }

    static {
      defaultInstance = new Crime(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bignerdranch.android.criminalintent.models.raw.Crime)
  }

  public interface CrimeLabOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bignerdranch.android.criminalintent.models.raw.CrimeLab)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> 
        getCrimesList();
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime getCrimes(int index);
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    int getCrimesCount();
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    java.util.List<? extends com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder> 
        getCrimesOrBuilderList();
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder getCrimesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.bignerdranch.android.criminalintent.models.raw.CrimeLab}
   */
  public static final class CrimeLab extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.bignerdranch.android.criminalintent.models.raw.CrimeLab)
      CrimeLabOrBuilder {
    // Use CrimeLab.newBuilder() to construct.
    private CrimeLab(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CrimeLab(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CrimeLab defaultInstance;
    public static CrimeLab getDefaultInstance() {
      return defaultInstance;
    }

    public CrimeLab getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CrimeLab(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                crimes_ = new java.util.ArrayList<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime>();
                mutable_bitField0_ |= 0x00000001;
              }
              crimes_.add(input.readMessage(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          crimes_ = java.util.Collections.unmodifiableList(crimes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.class, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.Builder.class);
    }

    public static com.google.protobuf.Parser<CrimeLab> PARSER =
        new com.google.protobuf.AbstractParser<CrimeLab>() {
      public CrimeLab parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CrimeLab(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CrimeLab> getParserForType() {
      return PARSER;
    }

    public static final int CRIMES_FIELD_NUMBER = 1;
    private java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> crimes_;
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    public java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> getCrimesList() {
      return crimes_;
    }
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    public java.util.List<? extends com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder> 
        getCrimesOrBuilderList() {
      return crimes_;
    }
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    public int getCrimesCount() {
      return crimes_.size();
    }
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime getCrimes(int index) {
      return crimes_.get(index);
    }
    /**
     * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
     */
    public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder getCrimesOrBuilder(
        int index) {
      return crimes_.get(index);
    }

    private void initFields() {
      crimes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCrimesCount(); i++) {
        if (!getCrimes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < crimes_.size(); i++) {
        output.writeMessage(1, crimes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < crimes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, crimes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bignerdranch.android.criminalintent.models.raw.CrimeLab}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bignerdranch.android.criminalintent.models.raw.CrimeLab)
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLabOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.class, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.Builder.class);
      }

      // Construct using com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCrimesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (crimesBuilder_ == null) {
          crimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          crimesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor;
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab getDefaultInstanceForType() {
        return com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.getDefaultInstance();
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab build() {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab buildPartial() {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab result = new com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab(this);
        int from_bitField0_ = bitField0_;
        if (crimesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            crimes_ = java.util.Collections.unmodifiableList(crimes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.crimes_ = crimes_;
        } else {
          result.crimes_ = crimesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab) {
          return mergeFrom((com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab other) {
        if (other == com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab.getDefaultInstance()) return this;
        if (crimesBuilder_ == null) {
          if (!other.crimes_.isEmpty()) {
            if (crimes_.isEmpty()) {
              crimes_ = other.crimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCrimesIsMutable();
              crimes_.addAll(other.crimes_);
            }
            onChanged();
          }
        } else {
          if (!other.crimes_.isEmpty()) {
            if (crimesBuilder_.isEmpty()) {
              crimesBuilder_.dispose();
              crimesBuilder_ = null;
              crimes_ = other.crimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              crimesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCrimesFieldBuilder() : null;
            } else {
              crimesBuilder_.addAllMessages(other.crimes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCrimesCount(); i++) {
          if (!getCrimes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeLab) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> crimes_ =
        java.util.Collections.emptyList();
      private void ensureCrimesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          crimes_ = new java.util.ArrayList<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime>(crimes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder> crimesBuilder_;

      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> getCrimesList() {
        if (crimesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(crimes_);
        } else {
          return crimesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public int getCrimesCount() {
        if (crimesBuilder_ == null) {
          return crimes_.size();
        } else {
          return crimesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime getCrimes(int index) {
        if (crimesBuilder_ == null) {
          return crimes_.get(index);
        } else {
          return crimesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder setCrimes(
          int index, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.set(index, value);
          onChanged();
        } else {
          crimesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder setCrimes(
          int index, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.set(index, builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder addCrimes(com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.add(value);
          onChanged();
        } else {
          crimesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          int index, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.add(index, value);
          onChanged();
        } else {
          crimesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.add(builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          int index, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.add(index, builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder addAllCrimes(
          java.lang.Iterable<? extends com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime> values) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, crimes_);
          onChanged();
        } else {
          crimesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder clearCrimes() {
        if (crimesBuilder_ == null) {
          crimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          crimesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public Builder removeCrimes(int index) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.remove(index);
          onChanged();
        } else {
          crimesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder getCrimesBuilder(
          int index) {
        return getCrimesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder getCrimesOrBuilder(
          int index) {
        if (crimesBuilder_ == null) {
          return crimes_.get(index);  } else {
          return crimesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public java.util.List<? extends com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder> 
           getCrimesOrBuilderList() {
        if (crimesBuilder_ != null) {
          return crimesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(crimes_);
        }
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder addCrimesBuilder() {
        return getCrimesFieldBuilder().addBuilder(
            com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder addCrimesBuilder(
          int index) {
        return getCrimesFieldBuilder().addBuilder(
            index, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.getDefaultInstance());
      }
      /**
       * <code>repeated .com.bignerdranch.android.criminalintent.models.raw.Crime crimes = 1;</code>
       */
      public java.util.List<com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder> 
           getCrimesBuilderList() {
        return getCrimesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder> 
          getCrimesFieldBuilder() {
        if (crimesBuilder_ == null) {
          crimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.Crime.Builder, com.bignerdranch.android.criminalintent.models.raw.CriminalIntentProtos.CrimeOrBuilder>(
                  crimes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          crimes_ = null;
        }
        return crimesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.bignerdranch.android.criminalintent.models.raw.CrimeLab)
    }

    static {
      defaultInstance = new CrimeLab(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bignerdranch.android.criminalintent.models.raw.CrimeLab)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%protobuf/criminal_intent_protos.proto\022" +
      "2com.bignerdranch.android.criminalintent" +
      ".models.raw\"G\n\005Crime\022\n\n\002id\030\001 \002(\t\022\r\n\005titl" +
      "e\030\002 \002(\t\022\023\n\013createdDate\030\003 \002(\003\022\016\n\006solved\030\004" +
      " \002(\010\"U\n\010CrimeLab\022I\n\006crimes\030\001 \003(\01329.com.b" +
      "ignerdranch.android.criminalintent.model" +
      "s.raw.Crime"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bignerdranch_android_criminalintent_models_raw_Crime_descriptor,
        new java.lang.String[] { "Id", "Title", "CreatedDate", "Solved", });
    internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bignerdranch_android_criminalintent_models_raw_CrimeLab_descriptor,
        new java.lang.String[] { "Crimes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
